### ISSUE TITLE
LocationEngine invoking listeners twice

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#429] opened 2017-04-01 20:08 UTC
### Steps to trigger behavior

 1. Create a locationEngine and add 1 listener 
 2. When location changes, the listener is called twice

### Expected behavior
listener only called once

### Actual behavior
Called twice.

cc: @zugaldia

**Comment by zugaldia** [comment] 2017-04-03 18:01
I'm not able to reproduce this one, at least with the `LocationEngineActivity` in the test app. When I use the Mock engine, for example, I get one update for each location:

![image](https://cloud.githubusercontent.com/assets/6964/24623158/851c246e-1875-11e7-93d0-cbfbde68404b.png)
_(note the different values for latitude)_

If I switch to Lost, I get the expected one update / second:

![image](https://cloud.githubusercontent.com/assets/6964/24623282/e18b5468-1875-11e7-8afd-87390c9f937f.png)
_(note the time in the logs)_

**Comment by cammace** [comment] 2017-04-05 21:03
```
04-05 16:57:36.256 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[network 38.909905,-77.036522 acc=25 et=+7d21h20m13s41ms {Bundle[mParcelledData.dataSize=624]}]
04-05 16:57:45.280 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[network 38.910036,-77.036252 acc=23 et=+7d21h20m41s243ms {Bundle[mParcelledData.dataSize=616]}]
04-05 16:57:45.329 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[network 38.910036,-77.036252 acc=23 et=+7d21h20m41s243ms {Bundle[mParcelledData.dataSize=616]}]
04-05 16:58:03.839 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036391 acc=22 et=+7d21h20m59s833ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=40]}]
04-05 16:58:03.863 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036391 acc=22 et=+7d21h20m59s833ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=492]}]
04-05 16:58:04.839 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036391 acc=21 et=+7d21h21m0s828ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=40]}]
04-05 16:58:04.878 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036391 acc=21 et=+7d21h21m0s828ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=492]}]
04-05 16:58:05.027 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[network 38.909887,-77.036546 acc=21 et=+7d21h21m1s15ms {Bundle[mParcelledData.dataSize=560]}]
04-05 16:58:05.879 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=14 et=+7d21h21m1s828ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=40]}]
04-05 16:58:06.013 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=14 et=+7d21h21m1s828ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=436]}]
04-05 16:58:06.827 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=14 et=+7d21h21m2s824ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=40]}]
04-05 16:58:06.875 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=14 et=+7d21h21m2s824ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=436]}]
04-05 16:58:07.828 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=14 et=+7d21h21m3s824ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=40]}]
04-05 16:58:07.860 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=14 et=+7d21h21m3s824ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=436]}]
04-05 16:58:08.841 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=15 et=+7d21h21m4s834ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=40]}]
04-05 16:58:08.873 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=15 et=+7d21h21m4s834ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=436]}]
04-05 16:58:09.839 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=16 et=+7d21h21m5s834ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=40]}]
04-05 16:58:09.961 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=16 et=+7d21h21m5s834ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=436]}]
04-05 16:58:10.847 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=16 et=+7d21h21m6s837ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=40]}]
04-05 16:58:10.939 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=16 et=+7d21h21m6s837ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=436]}]
04-05 16:58:11.833 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=17 et=+7d21h21m7s827ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=40]}]
04-05 16:58:11.898 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=17 et=+7d21h21m7s827ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=436]}]
04-05 16:58:12.826 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=18 et=+7d21h21m8s822ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=40]}]
04-05 16:58:12.902 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=18 et=+7d21h21m8s822ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=436]}]
04-05 16:58:13.841 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=20 et=+7d21h21m9s828ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=40]}]
04-05 16:58:13.881 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=20 et=+7d21h21m9s828ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=436]}]
04-05 16:58:14.844 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=20 et=+7d21h21m10s829ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=40]}]
04-05 16:58:14.894 4549-4549/com.mapbox.services.android.testapp D/LocationEngineActivity: New location received: Location[gps 38.909925,-77.036392 acc=20 et=+7d21h21m10s829ms alt=25.0 vel=0.0 {Bundle[mParcelledData.dataSize=436]}]
```

My logput looks like the above, you'll notice even though the times are different, i'm still getting duplicate updates. Only think I have modified in my locationEngineActivity was adding `locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);` at [this line](https://github.com/mapbox/mapbox-java/blob/master/mapbox/app/src/main/java/com/mapbox/services/android/testapp/location/LocationEngineActivity.java#L86)

**Comment by zugaldia** [comment] 2017-04-06 14:52
> Only thing I have modified in my locationEngineActivity was adding locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY); at this line

Does this still happen when `setPriority()` isn't set?

**Comment by cammace** [comment] 2017-04-06 14:53
No and it seems to happen when modifying any of the locationEngine default params.

**Comment by zugaldia** [comment] 2017-04-06 16:39
@cammace It looks like you're observing https://github.com/mapzen/lost/issues/142 which was fixed by https://github.com/mapzen/lost/pull/146. This is because the app has requests started from both MAS and the Maps SDK. We need to update MAS and the Maps SDK to 2.2.0 which is the release that includes the fix.

**Closed** 2017-04-06 17:23 UTC
Labels: bug
