### ISSUE TITLE
Reverse Geocoding Service not returning response in multiple languages

### ISSUE THREAD

**Issue by cbadhrinath** [mapbox/mapbox-java#923] opened 2018-11-14 16:31 UTC
I'm using the mapbox-sdk-services:4.1.0-SNAPSHOT for my Android project.

MapboxGeocoding.builder()
                            .accessToken("")
                            .query(Point.fromLngLat(-123.1207, 49.2827))
                            .languages(new Locale("ru"), new Locale("zh-CN"))
                            .geocodingTypes(GeocodingCriteria.TYPE_PLACE)
                            .mode(GeocodingCriteria.MODE_PLACES)
                            .build();
Still returning only one language. Not returing all requested language.
Could you please confirm this.

_Originally posted by @cbadhrinath in https://github.com/mapbox/mapbox-java/issues/446#issuecomment-438259691_

**Comment by osana** [comment] 2018-11-20 16:21
closing as a duplicate of #446

**Closed by osana** 2018-11-20 16:21 UTC
