### ISSUE TITLE
Sdk incorrectly applies rate-limit to optimization query

### ISSUE THREAD

**Issue by PureW** [mapbox/mapbox-java#1338] opened 2021-11-29 16:30 UTC
In https://github.com/mapbox/mapbox-java/blob/bf98d2125f02ec0e87b2d625d85a9b886ab7630c/services-optimization/src/main/java/com/mapbox/api/optimization/v1/MapboxOptimization.java#L479-L485 a 12 coordinate rate-limit is incorrectly applied to the optimization api.

The navigation-api has a 12 coordinate _default_ limit, but we often raise the limit on a per account basis. The sdk should defer to the http-api for rate limits for this reason.

cc @soleary91

**Comment by Guardiola31337** [comment] 2021-11-30 22:43
Dupe of https://github.com/mapbox/mapbox-java/issues/1157

**Closed** 2021-11-30 22:53 UTC
