### ISSUE TITLE
NoClassDefFoundError for BindingContextFactory in MapboxDirections.java

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-java#908] opened 2018-10-29 13:34 UTC
Seeing this in crash logs, it seems there's some sort of issue resolving the `BindingContextFactory`.  

```
Fatal Exception: java.lang.NoClassDefFoundError
Failed resolution of: Lcom/sun/xml/internal/ws/spi/db/BindingContextFactory;
    com.mapbox.api.directions.v5.MapboxDirections.errorDidOccur (MapboxDirections.java:194)
    com.mapbox.api.directions.v5.MapboxDirections.access$000 (MapboxDirections.java:60)
    com.mapbox.api.directions.v5.MapboxDirections$1.onResponse (MapboxDirections.java:146)
    retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run (ExecutorCallAdapterFactory.java:70)
```

When navigating to `MapboxDirections.java` in the Navigation SDK codebase I see:
![screen shot 2018-10-29 at 9 20 15 am](https://user-images.githubusercontent.com/8434572/47652952-b7fc3200-db5d-11e8-8ffa-d820fee80c4d.png)

@osana @zugaldia could this be some sort of dependency conflict in the navigation repo?

**Comment by zugaldia** [comment] 2018-10-29 14:47
@danesfeder I think this is related to a ProGuard setting that we cannot include in this project (because it's a pure Java project) but that @tobrun recently added with https://github.com/mapbox/mapbox-gl-native/pull/13103. Could you try with a nav build including that ProGuard rule, or not using ProGuard at all?

**Comment by danesfeder** [comment] 2018-10-29 14:51
@zugaldia ah okay thank you - I'll give that a shot!

**Comment by danesfeder** [comment] 2018-10-29 15:02
Hmm it looks like we are including this already https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/proguard-consumer.pro#L13

cc @Guardiola31337

**Comment by Guardiola31337** [comment] 2018-10-29 17:19
@zugaldia @danesfeder the `dontwarn` Proguard rule doesn't fix this - actually, it hides it until it crashes at runtime. This was introduced by https://github.com/mapbox/mapbox-java/pull/758 and https://github.com/mapbox/mapbox-java/pull/765 

The problem here is that we're using a class (`BindingContextFactory` - I guess it's included in some JDKs) which is not available on Android. So when the exception is thrown at runtime Android is not able to find that class and 💥 

We should ensure that we use a logger that's available in Android. I'll cut a PR using the Java [`Logger`](https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html) (that should be available in Android) instead of using `BindingContextFactory` from `sun` library. After fixing this I believe that Proguard rule won't be necessary anymore so we'll need to remove it from the different projects in which is included (I'll remark this in the PR).

BTW this is duplicate of https://github.com/mapbox/mapbox-java/issues/852 so I'm going to go ahead and close here.

Thanks for flagging!

**Closed by Guardiola31337** 2018-10-29 17:19 UTC
Labels: Directions

**Comment by osana** [comment] 2018-10-29 17:20
@Guardiola31337 I agree that it is very easy to get rid of `BindingContextFactory`.  I just do it. There is no good reason to use `BindingContextFactory`.

**Comment by osana** [comment] 2018-10-29 17:38
@danesfeder  @Guardiola31337  
https://github.com/mapbox/mapbox-java/pull/909 will address this
