### ISSUE TITLE
Latest nightly snapshot (12/12/16) puts my location marker @ Antarctica

### ISSUE THREAD

**Issue by yperess** [mapbox/mapbox-java#241] opened 2016-12-13 04:14 UTC
When initializing a MapView with `app:my_location_enabled="true"` and tracking set to follow. My location marker doesn't show and the camera is focused on Antarctica. If I add `map.setMyLocationEnabled(true);` to the `onMapReady` callback then my location marker does show, but still in Antarctica.

The odd thing is that `onMyLocationChangeListener` reports the correct GPS location.

**Comment by cammace** [comment] 2016-12-14 21:38
I'm not able to reproduce this issue on `4.2.0`. One thing to note is that if you enable tracking, you don't need to enable location. Try upgrading and testing out and if you still are having issues, please reach out through our [contact page](https://www.mapbox.com/contact/) or in the correct repo https://github.com/mapbox/mapbox-gl-native/issues. Closing since this issue isn't relevant to this repo.

**Closed by cammace** 2016-12-14 21:38 UTC
