### ISSUE TITLE
Nullability of Feature properties

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#880] opened 2018-09-03 11:55 UTC
Reposting from issue downstream in https://github.com/mapbox/mapbox-gl-native/issues/12744: 

----

Have not actually experienced any problems, but the code shows how it could happen.

In `com.mapbox.geojson.Feature` the `properties` method is annotated as `Nullable`.  The `getStringProperty` and others like it deferences the returned value with out checking for null.

**Android versions:** N/A
**Device models:** N/A
**Mapbox SDK versions:** 6.4.0

**Comment by osana** [comment] 2018-09-05 04:11
This is related to https://github.com/mapbox/mapbox-java/issues/813

According to GeoJson spec properties must have @Nullable annotation:
     A Feature object has a member with the name "properties".  The
      value of the properties member is an object (any JSON object or a
      JSON null value).

As it is correctly pointed out Feature has several convenience  methods to modify properties.  For those methods to work we have to create an empty JsonObject whenever null is passed for properties into the factory methods. 

Please note that toJson will serialize empty JsonObject (properties) as null and fromJson will create empty JsonObject whenever property is null in the json string. 

Closing as not a bug.

**Comment by osana** [comment] 2018-09-05 04:15
Actually there needs to be a fix in one line:
https://github.com/mapbox/mapbox-java/blob/9fa87fb4c1b1ae82acdb44fec4a8d488821c3cc5/services-geojson/src/main/java/com/mapbox/geojson/Feature.java#L168

it should be:    
```return new AutoValue_Feature(TYPE, bbox, id, geometry, properties == null ? new JsonObject() : properties);```

**Comment by osana** [comment] 2018-11-01 16:15
@tobrun  Are you ok  to close it , given above context

**Comment by osana** [comment] 2018-12-18 21:17
Closing as all related work to this pr was done

**Closed by osana** 2018-12-18 21:17 UTC
Labels: GeoJson
