### ISSUE TITLE
Add TurfBuffer

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#1130] opened 2020-03-19 09:19 UTC
Implement: https://turfjs.org/docs/#buffer
https://github.com/Turfjs/turf/tree/master/packages/turf-buffer

**Comment by langsmith** [comment] 2020-03-19 14:32
Duplicate of https://github.com/mapbox/mapbox-java/issues/987

**Closed by langsmith** 2020-03-19 14:32 UTC
Labels: Turf
