### ISSUE TITLE
Allow multiple locales

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#511] opened 2017-07-15 01:14 UTC
> Apparently the language parameter will accept multiple IETF language tags, separated by commas. We should replace the locale property on GeocodeOptions with a locales property of type `[Locale]`.

https://github.com/mapbox/MapboxGeocoder.swift/issues/104

**Comment by 1ec5** [comment] 2017-07-15 01:31
Duplicate of #446 (using GitHub’s new keyword feature for the first time).

**Closed by 1ec5** 2017-07-15 01:31 UTC
Labels: geocoding
