### ISSUE TITLE
Map Matching issue with request containing waypoint indices

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-java#849] opened 2018-07-11 18:17 UTC
_Originally opened in Navigation SDK:_ https://github.com/mapbox/mapbox-navigation-android/issues/1085

**Android API: 7.0
**Mapbox Navigation SDK version:6.1.3

### Steps to trigger behavior

 1. Request a route using Mapbox map matching builder with specified waypoints
 2. No matches are found

I want to request custom routes using Mapbox map matching but I only want the first and last (origin and destination) coordinates to be displayed as "waypoints" in the matched DirectionsRoute. When I request a route with these two coordinates specified as waypoints I do not receive a match. However, when I do not specify waypoints in my request I receive an accurate DirectionsRoute response.   

Builder with waypoints specified(no matched route):

```
 MapboxMapMatching.builder()
                .coordinates(coordinateList)
                .steps(true)
                .waypoints(0, coordinateList.size()-1)
                .accessToken(MAPBOX_ACCESS_TOKEN)
                .voiceInstructions(true)
                .bannerInstructions(true)
                .profile(DirectionsCriteria.PROFILE_WALKING)
                .build()
```

Builder with no waypoints specified(correct matched directions route):

```
 MapboxMapMatching.builder()
                .coordinates(coordinateList)
                .steps(true)
                .accessToken(MAPBOX_ACCESS_TOKEN)
                .voiceInstructions(true)
                .bannerInstructions(true)
                .profile(DirectionsCriteria.PROFILE_WALKING)
                .build()
```

**Comment by danesfeder** [comment] 2018-07-16 13:22
Capturing chat with @danpat - if you have `waypoints=0;<last>`, it requires that the match is complete from start to finish, so it looks like this isn't an issue with MAS here.

**Comment by jackhd1** [comment] 2018-07-16 17:53
@danesfeder Can you clarify the requirement that "the match is complete from start to finish"? Our list of coordinates that we pass to the MapboxMapMatching builder consists of Longitude and Latitudes of a complete route that we verified is correct by plotting it in QGIS. Our issue is when we break up the route into separate requests to comply with the 100 point limit some of the segments return no match. We have been able to locate trouble segments of 5-10 points that cause NoMatch to be returned. We have verified that these points comply with OSM data for this route. We need to use MapboxMapMatching to get a DirectionsRoute object to use for MapboxNavigation.

**Comment by jackhd1** [comment] 2018-07-18 13:38
@danpat Here is a trouble segment with a distance of around half a mile: 

`-80.398462, 37.190151; -80.398805, 37.190084; -80.39891, 37.190294; -80.399652, 37.19169; -80.400033, 37.192244; -80.400369, 37.192691; -80.400468, 37.193149`

I believe the match on this segment of points is failing because of the proximity of an adjacent road. Thanks for your help.

**Comment by danpat** [comment] 2018-07-18 14:51
@jackhd1 The problem is that Transportation Research Drive is marked as private - https://www.openstreetmap.org/way/51274762.  The matching algorithm won't consider private roads like this.

I think could probably be argued that it should - if you have a recorded GPS trace or a pre-planned path that traverses private roads, that's sufficient assertion that you're allowed access to them, at least in the map-matching case.

I'll open an internal discussion about this.  Changing this behaviour would require some fairly large changes in our system, so it won't be something we change quickly, but I'll try to get it on the roadmap for future updates to the service.

**Comment by jackhd1** [comment] 2018-07-18 15:11
@danpat Okay that makes sense. I have found a work around for now using the NavigationRoute API on the trouble segment. Thanks for looking into this for me.

**Comment by osana** [comment] 2018-09-13 16:39
nothing to address in this repo - closing the issue

**Closed by osana** 2018-09-13 16:39 UTC
Labels: Directions, Map Matching

**Comment by rdvelazquez** [comment] 2020-03-03 21:45
@danpat Any updates on allowing the matching algorithm to consider private roads? We are currently running into the same issue.
