### ISSUE TITLE
Map starts to drift without location change

### ISSUE THREAD

**Issue by yperess** [mapbox/mapbox-java#239] opened 2016-12-10 11:43 UTC
Please see my question on http://stackoverflow.com/questions/41075118/mapbox-my-location-drift-android

Effectively, the map starts to look like I'm walking when I'm getting no location updates from either mapbox or the location manager.

**Comment by yperess** [comment] 2016-12-11 12:10
OK, so I've realized this was actually 2 issues which I thought was just one. The self marker drifting away from the camera was fixed by adding a call to `setDismissLocationTrackingOnGesture(false)` because tracking kept being turned off by every update. While the camera follows the self marker now, it's still drifting a lot if I don't have a strong GPS signal.

**Comment by cammace** [comment] 2016-12-14 21:41
> if I don't have a strong GPS signal

This is probably the issue, I'm not able to reproduce this issue either. A GIF of this issue or any additional code will help. Closing as this ticket doesn't belong in this repo either but in [GL-native](https://github.com/mapbox/mapbox-gl-native/issues)

**Closed by cammace** 2016-12-14 21:41 UTC
